### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by AaruBama**
solves #66

### CODE REVIEW

**Comment by nemanjaglumac** [comment]
If you want to link a PR to an issue and automatically close it, use these keywords:
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests

**Comment by AaruBama** [comment]
fixes #66

**Comment by nemanjaglumac** [comment]
> fixes https://github.com/AaruBama/memestr/issues/66

@AaruBama for the future reference, this needs to be in the PR description, not in a comment. Once you do it correctly, you'll see a link between a PR and an issue in this section
image

**Comment by AaruBama** [comment]
Understood @nemanjaglumac . 

I'm really learning lot of GitHub things I never considered too useful, around you.

**Pull request merged**
