### PR TITLE
Introduce code formatting to the project

### PR DESCRIPTION
**Pull request by nemanjaglumac**
The project is missing some crucial configurations that make collaborative work much easier, and friction free.
`.editorconfig` is the very minimum you should add, even if you decide to reject everything else.

But since `prettier` is already installed, why not add its config as well?
30bbaa0b43fb4b0c26e07d81957d68a5e751c0af does exactly that.

This PR touches a lot of files, but that's only because I had to format everything according to these rules.
But once these rules are all in place, every new contributor (including yourself @AaruBama ) will have auto-formatted code and the diff will be focused only on changed lines. This makes code reviews much easier and more enjoyable.

> **Note**
> Auto-formatting applies ONLY if each contributor has enabled "format on save" in their IDE.

**If you want to ensure that all commits are formatted properly, I suggest adding precommit hooks that'll take care of that.**
If that sounds like a good idea to you, I can do it in the next PR.

### CODE REVIEW

**Comment by abhay-raizada** [comment]
this is awesome!, we can even add some linter checks at PR level so it fails PRs that are not linted correctly, so we're not relying on developers to be careful, i'm even okay with a pre-commit hook (should make an issue out of it).

**Comment by nemanjaglumac** [comment]
Thank you for creating an issue. @abhay-raizada 

I'll take care of that after this PR gets merged.

**Comment by AaruBama** [comment]
Awesome Man! Truly appreciate your help here.
Not only code is more structured and readable now, it'd also work as standard for any upcoming commits (specially with @abhay-raizada prehook commit) from all devs.

Mucha Gracias Senór! 🤠 @nemanjaglumac

**Comment by AaruBama** [comment]
I'll merge this tomorrow along with the other PR and some more categories on the way! I think on this weekend, we'd have better looking Modals for Navbar and a decent looking Dekstop site.

**Pull request merged**
