### PR TITLE
Delete dead libraries

### PR DESCRIPTION
**Pull request by nemanjaglumac**
There are a lot of libraries which are not used.
I had the dev environment running all the time while cleaning these up, and haven't seen a single change in a website.

But it's quite possible I missed something so check carefully.
From the code perspective alone, I haven't seen references to these libraries so I assume they are not used.

### CODE REVIEW

**Comment by AaruBama** [comment]
@nemanjaglumac Just curious, do you use memestr sometimes?

**Comment by nemanjaglumac** [comment]
Sometimes is the right word.
Why?
Is that related to this PR? Did I miss something?

**Comment by AaruBama** [comment]
> Sometimes is the right word. Why? Is that related to this PR? Did I miss something?

No, The PR is absolutely fine. Just a few dependencies I have to ensure are not in use.
I just wanted to understand the motivation behind contributing to the project. 😅 

I remember our discussion from the post on Bolt.fun where I mentioned a bounty as well. So I was just wondering if maybe I could stop looking out for someone to assist us with the bugs in the project and offer you the 100K sats only as my gratitude.

**Comment by nemanjaglumac** [comment]
> I just wanted to understand the motivation behind contributing to the project.

I love open-source. I love Nostr. And I love memes.
I didn't know about this project. When I saw it on bolt.fun, I saw a lot of room for improvement, so I jumped in.
My genuine wish is to try to help the FOSS community.

I hope that some of my PRs, or issues have hopefully even been educational.
This all gave me an idea for an article for bolt.fun. Coming soon... :)

**Comment by AaruBama** [comment]
> I hope that some of my PRs, or issues have hopefully even been educational. 

They very certainly have been. A lot of things that I didn't even know that I had to improve as such priority. I understood the importance of these PRs from you I realized right after seeing the changes. You've been truly a wonderful help from project as well as personal improvements.

> This all gave me an idea for an article for bolt.fun. Coming soon... :)

I'm definitely looking forward to it. :D

**Comment by nemanjaglumac** [comment]
Should I close this PR?

**Pull request merged**
