### PR TITLE
Get rid of analytics

### LINKED ISSUE #48: Get rid of Google Analytics
This is a Nostr project.
This is FOSS project.

You should strive to compose it using only FOSS libraries.
Google as a company and Nostr as an idea couldn't be further apart.

I'd say that you don't really need analytics in the early stages, but that's up to you.
If you decide that you absolutely need it, at least research some FOSS Google Analytics alternatives that respect privacy.

There should be plenty.

### PR DESCRIPTION
**Pull request by nemanjaglumac**
This is highly opinionated PR.
Not expecting you to merge it if it doesn't align with the direction you wanted to move this project forward.

Resolves #48

### CODE REVIEW

**Comment by AaruBama** [comment]
@nemanjaglumac You're very kind. Thank you so much for this PR.

I personally like to know just the absolute essentials in the early stages of any startup and keep it as a balance.

@nemanjaglumac  @abhay-raizada What are your thoughts on analytics for the early stages.

**Comment by nemanjaglumac** [comment]
Until you get the proejct to a decently usable and decently looking state, you most likely don't need to track anything.
Analytics help you shape the product and develop (or remove) certain features.

It's better to focus on polishing UX and working on a DX in the beginning, without worrying about analytics.
But those are just my 2c.

Btw, a good metric to keep an eye on is number of Github starts and GitHub forks. That doesn't give you the complete picture because a good portion of your users might not even have Google. Worry about it when the project reaches at least 100 stars.

**Comment by abhay-raizada** [comment]
It's your choice/style whether you want to keep analytics in your  project or not but i highly agree with @nemanjaglumac that it should align with the ethos of nostr and FOSS, maybe we could do some nostr-native tracking that you feel is absolutely essential for the project, or atleast use some other analytics tool that respects user privacy.

**Comment by AaruBama** [comment]
Understood.
I wanted to see the engagement of users from time to time to see what feature is driving what amount of users. I think I have gotten an idea which should suffice for now.

Later we can add analytics when the project looks in better shape.

**Pull request merged**
